### ISSUE TITLE
Subnet creation to be parameterized better

### ISSUE THREAD

**Issue by phx-tim-butters** [Azure/terraform-azurerm-avm-ptn-vnetgateway#24] opened 2024-03-06 11:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are predominantly throwing in a Subnet ID to the module to associate the gateway to an existing subnet. 

However, sometimes this subnet ID is calculated and won't be known until Apply.

This causes an issue in running a Plan when using the module, as the var.subnet_id needs to be known for the count to run within the module

In a similar sense to how the route_table_creation_enabled boolean exists, I would suggest a variable for subnet creation is also created to allow us to circumvent this issue.

### New or Affected Resource(s)/Data Source(s)

resource "azurerm_subnet" "vgw"

### Potential Terraform Configuration

```hcl
main.tf

resource "azurerm_subnet" "vgw" {
  count = var.subnet_creation_enabled ? 1 : 0

  address_prefixes     = [var.subnet_address_prefix]
  name                 = "GatewaySubnet"
  resource_group_name  = var.virtual_network_resource_group_name
  virtual_network_name = var.virtual_network_name
}

varables.tf

variable "subnet_creation_enabled" {
  type        = bool
  default     = false
  description = "Whether to create a Subnet or whether one is being passed in"
}
```

**Comment by luke-taylor** [comment] 2024-03-12 15:59
Duplicate of #19

**Closed by luke-taylor** 2024-03-12 15:59 UTC
Labels: Type: Duplicate :palms_up_together:
